<a href="https://colab.research.google.com/github/Harish-aditya/DeepLearning_using-_Pytorch./blob/main/Deep_learning_using_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import Functions.

In [1]:
from __future__ import print_function
import torch

Pytorch compared to NumPy
Matrix formation using Pytorch

In [2]:
torch.tensor([[2,3,5],[1,2,9]])

tensor([[2, 3, 5],
        [1, 2, 9]])

In [3]:
torch.rand(2,2)

tensor([[0.4204, 0.4850],
        [0.1824, 0.7021]])

In [4]:
a = torch.rand((3,5))
a

tensor([[0.6165, 0.2164, 0.2052, 0.6344, 0.7383],
        [0.5300, 0.1969, 0.4243, 0.5493, 0.1936],
        [0.1693, 0.3276, 0.6333, 0.2224, 0.8085]])

In [5]:
a.shape

torch.Size([3, 5])

Matrix formation using numpy

In [6]:
import numpy as np
np.array([[2,3,4],[1,2,3]])

array([[2, 3, 4],
       [1, 2, 3]])

In [7]:
np.random.rand(2,2)

array([[0.84380047, 0.69535017],
       [0.79233397, 0.33940478]])

# Construct a randomly initialized matrix and operation using Pytorch

In [8]:
a = torch.rand((2,2))
b = torch.rand((2,2))

In [9]:
torch.matmul(a,b)

tensor([[1.0011, 0.8247],
        [0.8544, 0.9037]])

In [10]:
a*b

tensor([[0.3055, 0.8007],
        [0.6793, 0.1217]])

In [11]:
a

tensor([[0.6954, 0.8554],
        [0.8354, 0.5994]])

In [12]:
a

tensor([[0.6954, 0.8554],
        [0.8354, 0.5994]])

Construct a randomly initialized matrix and operation using NumPy

In [13]:
a = np.random.rand(2,2)
b = np.random.rand(2,2)

In [14]:
np.dot(a,b)
# normal matrix multiplication
# Where the condition of number of columns of first array should be equal to number of rows of second array is checked.
# then only numpy.dot() function take place else it throws an error.

array([[0.29780289, 0.18038665],
       [0.18215066, 0.12172014]])

In [15]:
np.multiply(a,b)
# '*' 
# element wise multiplication

array([[0.05387924, 0.02851333],
       [0.01674845, 0.11976234]])

### Construct a 5x3 matrix uninitialized:

In [16]:
x = torch.empty(5,3)

In [17]:
x

tensor([[1.1985e-34, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 0.0000e+00]])

### Construct a matrix filled zeros and of dtypes long:

In [18]:
y = torch.zeros((2,2))
y

tensor([[0., 0.],
        [0., 0.]])

In [19]:
y_num = np.zeros((2,2))
y_num

array([[0., 0.],
       [0., 0.]])

In [20]:
x = torch.zeros(5,3,dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


### Construct a matrix of ones

In [21]:
o = torch.ones(2,2)

In [22]:
o

tensor([[1., 1.],
        [1., 1.]])

In [23]:
o_num = np.ones((2,2))
o_num

array([[1., 1.],
       [1., 1.]])

### Construst identity matrix

In [24]:
c_num = np.identity(5)
c_num

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
c = torch.eye(2)
c

tensor([[1., 0.],
        [0., 1.]])

## Converting NumPy array to torch tensor see how changing the np array changed the Torch Tensor automatically

In [26]:
d = torch.from_numpy(c_num)

In [27]:
d

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]], dtype=torch.float64)

In [28]:
d_num = c.numpy()
d_num

array([[1., 0.],
       [0., 1.]], dtype=float32)

## create a tensor based on an existing tensor.

In [29]:
x1 = x.new_ones(5,3, dtype=torch.double)
print(x1)

x2 = x.new_ones(5,3, dtype=torch.float)
print(x2)

x3 = torch.randn_like(x, dtype = float)
print(x3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[ 0.0289,  0.4783, -0.1529],
        [ 2.3885,  1.2762,  0.5646],
        [-0.7194,  0.0427,  0.0385],
        [ 0.8869,  1.4669,  0.3163],
        [ 0.6660,  0.2885,  0.4383]], dtype=torch.float64)


Size of the array of tensors.

In [30]:
print(x.size())

torch.Size([5, 3])


"torch size" is in fact a tuple, so it supports all tuple operations.
Operations There are multiple syntaxes for operations. In the following example, we will take a look at the addition operations

In [31]:
y = torch.rand(2,2)
print(o,"\n",y)
print(o+y)

tensor([[1., 1.],
        [1., 1.]]) 
 tensor([[0.2103, 0.0497],
        [0.5517, 0.6204]])
tensor([[1.2103, 1.0497],
        [1.5517, 1.6204]])


In [32]:
torch.add(o,y)

tensor([[1.2103, 1.0497],
        [1.5517, 1.6204]])

using out option to get output as arguement

In [33]:
result = torch.empty(2,2)
torch.add(o,y,out = result)
result

tensor([[1.2103, 1.0497],
        [1.5517, 1.6204]])

Adding in place.

In [34]:
o.add_(y)

tensor([[1.2103, 1.0497],
        [1.5517, 1.6204]])

Note:
Any operation that mutates a tensor in-place is post-fixed with an "_". for example: "x.copy_(y)" 

In [35]:
index = torch.rand(5,5)
index

tensor([[0.3275, 0.2180, 0.4198, 0.8128, 0.3298],
        [0.5979, 0.8514, 0.2406, 0.4438, 0.0225],
        [0.7740, 0.7629, 0.0930, 0.5006, 0.0703],
        [0.1283, 0.8757, 0.5668, 0.3961, 0.5167],
        [0.9736, 0.7785, 0.6097, 0.7452, 0.2128]])

In [36]:
index[:,0]

tensor([0.3275, 0.5979, 0.7740, 0.1283, 0.9736])

Resizing: If you want to resize/reshape tensor, you can use torch.view:

In [37]:
x2 = torch.randn(4,4)
y = x2.view(16)

z = x2.view(-1,4)# -1 helps tensor to reshape it in required manner according to
# second arguement (4) .
print(x2,y,z,sep = "\n")
print(x2.size(),y.size(),z.size())

tensor([[ 1.1725, -0.0039, -0.5651,  0.8715],
        [-1.1822, -0.4391,  0.8540, -0.7676],
        [-0.3695,  0.6197,  0.1415, -0.4697],
        [ 0.3995, -1.0070,  0.0795, -0.3352]])
tensor([ 1.1725, -0.0039, -0.5651,  0.8715, -1.1822, -0.4391,  0.8540, -0.7676,
        -0.3695,  0.6197,  0.1415, -0.4697,  0.3995, -1.0070,  0.0795, -0.3352])
tensor([[ 1.1725, -0.0039, -0.5651,  0.8715],
        [-1.1822, -0.4391,  0.8540, -0.7676],
        [-0.3695,  0.6197,  0.1415, -0.4697],
        [ 0.3995, -1.0070,  0.0795, -0.3352]])
torch.Size([4, 4]) torch.Size([16]) torch.Size([4, 4])


NumPy.random.randn generates samples from the normal distribution (mean 0 and variance 1), while numpy.rand from a uniform distribution (in the range [0,1)).

if you have a one element tensor, use .item() to get the value as a pythong number

In [38]:
x = torch.randn(1)
x
print(x.item())

-0.0464746318757534


Read later:
There are more than 100 operations including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc., are described
https://pytorch.org/docs/stable/index.html

NumPy Bridge
Converting a torch tensor to a numpy array and vice versa its a breeze.


The torch tensor and Numpy array will share their underlying memory locations.(if the torch tensor is on CPU), and changing one will change the other.

In [39]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [40]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

See how the numpy array changed in value.

In [41]:
a.add_(1)
print(a,b)

tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]


In [42]:
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1.4,out = a)

array([2.4, 2.4, 2.4, 2.4, 2.4])

## CUDA Tensors

In [43]:
#let us run this cell only if cuda is available
# we will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
  device = torch.device("cuda")
  y = torch.ones_like(x,device = device)
  x = x.to(device)
  print(z)
  print(z.to("cpu", torch.double))

Forward Propogation

In [45]:
a = torch.Tensor([2])
b = torch.Tensor([-4])
c = torch.Tensor([-2])
d = torch.Tensor([2])

e = a+b
f = c*d

g = e*f
print(e,f,g)

tensor([-2.]) tensor([-4.]) tensor([8.])


In [51]:
x = torch.tensor(-3., requires_grad=True)
y = torch.tensor(5., requires_grad=True)
z = torch.tensor(-1., requires_grad=True)

q = x + y
f = q * z
f.backward()
print("Gradient of z,y,x are:"+str(z.grad)+str(y.grad)+str(x.grad))

Gradient of z,y,x are:tensor(2.)tensor(-1.)tensor(-1.)


Fully Connected neural networks.

In [52]:
import torch
input_layer = torch.rand(10)# declaration of inputs
w1 = torch.rand(10,20)
w2 = torch.rand(20,20)
w3 = torch.rand(20,4)

h1 = torch.matmul(input_layer,w1)# first hidden layer.
h2 = torch.matmul(h1,w2)# subsequent hidden layer.
output_layer = torch.matmul(h2,w3)

print(h1,h2,output_layer,sep = "\n")

tensor([2.8828, 2.3721, 3.3445, 3.1905, 2.8747, 2.0490, 2.8308, 2.2947, 2.4581,
        2.6624, 2.5035, 2.2328, 2.9671, 3.2435, 2.5600, 2.2667, 2.2941, 1.6778,
        2.0018, 2.5875])
tensor([28.3993, 24.3472, 23.1005, 22.7352, 23.8806, 27.5794, 20.7466, 23.8700,
        27.6063, 19.2883, 30.3447, 20.5951, 27.5912, 24.5500, 23.3259, 23.6890,
        25.4389, 25.0883, 30.7696, 19.7363])
tensor([262.2821, 243.0472, 245.0803, 255.9052])


Building a neural network - Pytorch style

In [54]:
import torch.nn as nn
class Net(nn.Module):
  def __init__(self):
    super(Net, self).__init__()
    self.fc1 = nn.Linear(10,20)
    self.fc2 = nn.Linear(20,20)
    self.output = nn.Linear(20,4)


  def forward(self,x):
    x = self.fc1(x)
    x = self.fc2(x)
    x = self.output(x)
    return x


input_layer = torch.rand(10)
net = Net()
result = net(input_layer)

In [55]:
result

tensor([-0.3017, -0.0238, -0.1553, -0.1947], grad_fn=<AddBackward0>)