<a href="https://colab.research.google.com/github/Harish-aditya/DeepLearning_using-_Pytorch./blob/main/Deep_learning_using_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import Functions.

In [ ]:
from __future__ import print_function
import torch

Pytorch compared to NumPy
Matrix formation using Pytorch

In [ ]:
torch.tensor([[2,3,5],[1,2,9]])

tensor([[2, 3, 5],
        [1, 2, 9]])

In [ ]:
torch.rand(2,2)

tensor([[0.0417, 0.3599],
        [0.3639, 0.1464]])

In [ ]:
a = torch.rand((3,5))
a

tensor([[0.7975, 0.5333, 0.3637, 0.1565, 0.6207],
        [0.7823, 0.0737, 0.6247, 0.0054, 0.3446],
        [0.7099, 0.8864, 0.8046, 0.4897, 0.3765]])

In [ ]:
a.shape

torch.Size([3, 5])

Matrix formation using numpy

In [ ]:
import numpy as np
np.array([[2,3,4],[1,2,3]])

array([[2, 3, 4],
       [1, 2, 3]])

In [ ]:
np.random.rand(2,2)

array([[0.38562512, 0.01168776],
       [0.3485075 , 0.34285862]])

# Construct a randomly initialized matrix and operation using Pytorch

In [ ]:
a = torch.rand((2,2))
b = torch.rand((2,2))

In [ ]:
torch.matmul(a,b)

tensor([[0.1111, 0.4663],
        [0.0836, 0.3634]])

In [ ]:
a*b

tensor([[0.0150, 0.0486],
        [0.2044, 0.2601]])

In [ ]:
a

tensor([[0.7599, 0.3956],
        [0.8413, 0.2759]])

In [ ]:
a

tensor([[0.7599, 0.3956],
        [0.8413, 0.2759]])

Construct a randomly initialized matrix and operation using NumPy

In [ ]:
a = np.random.rand(2,2)
b = np.random.rand(2,2)

In [ ]:
np.dot(a,b)
# normal matrix multiplication
# Where the condition of number of columns of first array should be equal to number of rows of second array is checked.
# then only numpy.dot() function take place else it throws an error.

array([[0.62231735, 0.40266396],
       [1.06991177, 0.72037025]])

In [ ]:
np.multiply(a,b)

array([[0.04602721, 0.56073218],
       [0.73631319, 0.00393513]])