<a href="https://colab.research.google.com/github/Harish-aditya/DeepLearning_using-_Pytorch./blob/main/Deep_learning_using_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import Functions.

In [1]:
from __future__ import print_function
import torch

Pytorch compared to NumPy
Matrix formation using Pytorch

In [2]:
torch.tensor([[2,3,5],[1,2,9]])

tensor([[2, 3, 5],
        [1, 2, 9]])

In [3]:
torch.rand(2,2)

tensor([[0.2230, 0.8511],
        [0.4853, 0.1175]])

In [4]:
a = torch.rand((3,5))
a

tensor([[0.6711, 0.5028, 0.6296, 0.2790, 0.5140],
        [0.7401, 0.7805, 0.7861, 0.9155, 0.3154],
        [0.4362, 0.7878, 0.2695, 0.6655, 0.4432]])

In [5]:
a.shape

torch.Size([3, 5])

Matrix formation using numpy

In [6]:
import numpy as np
np.array([[2,3,4],[1,2,3]])

array([[2, 3, 4],
       [1, 2, 3]])

In [7]:
np.random.rand(2,2)

array([[0.35752453, 0.54426411],
       [0.12484242, 0.42776129]])

# Construct a randomly initialized matrix and operation using Pytorch

In [8]:
a = torch.rand((2,2))
b = torch.rand((2,2))

In [9]:
torch.matmul(a,b)

tensor([[0.1392, 0.1119],
        [0.4498, 0.3314]])

In [10]:
a*b

tensor([[0.0792, 0.0858],
        [0.1379, 0.1345]])

In [11]:
a

tensor([[0.2140, 0.2286],
        [0.5249, 0.9731]])

In [12]:
a

tensor([[0.2140, 0.2286],
        [0.5249, 0.9731]])

Construct a randomly initialized matrix and operation using NumPy

In [13]:
a = np.random.rand(2,2)
b = np.random.rand(2,2)

In [14]:
np.dot(a,b)
# normal matrix multiplication
# Where the condition of number of columns of first array should be equal to number of rows of second array is checked.
# then only numpy.dot() function take place else it throws an error.

array([[0.27939508, 0.20752195],
       [0.20936753, 0.08103336]])

In [15]:
np.multiply(a,b)
# '*' 
# element wise multiplication

array([[0.22616308, 0.02332422],
       [0.17001386, 0.00653982]])

### Construct a 5x3 matrix uninitialized:

In [16]:
x = torch.empty(5,3)

In [17]:
x

tensor([[4.3621e-35, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 0.0000e+00]])

### Construct a matrix filled zeros and of dtypes long:

In [18]:
y = torch.zeros((2,2))
y

tensor([[0., 0.],
        [0., 0.]])

In [19]:
y_num = np.zeros((2,2))
y_num

array([[0., 0.],
       [0., 0.]])

In [20]:
x = torch.zeros(5,3,dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


### Construct a matrix of ones

In [21]:
o = torch.ones(2,2)

In [22]:
o

tensor([[1., 1.],
        [1., 1.]])

In [23]:
o_num = np.ones((2,2))
o_num

array([[1., 1.],
       [1., 1.]])

### Construst identity matrix

In [24]:
c_num = np.identity(5)
c_num

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
c = torch.eye(2)
c

tensor([[1., 0.],
        [0., 1.]])

## Converting NumPy array to torch tensor see how changing the np array changed the Torch Tensor automatically

In [26]:
d = torch.from_numpy(c_num)

In [27]:
d

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]], dtype=torch.float64)

In [28]:
d_num = c.numpy()
d_num

array([[1., 0.],
       [0., 1.]], dtype=float32)

## create a tensor based on an existing tensor.

In [29]:
x1 = x.new_ones(5,3, dtype=torch.double)
print(x1)

x2 = x.new_ones(5,3, dtype=torch.float)
print(x2)

x3 = torch.randn_like(x, dtype = float)
print(x3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[ 0.2322,  1.0733,  0.9357],
        [-0.2983,  0.4342, -0.0062],
        [ 0.0503, -1.2984, -1.4845],
        [-0.3955, -0.4501,  0.8180],
        [-0.5743,  1.3128, -1.1909]], dtype=torch.float64)


Size of the array of tensors.

In [30]:
print(x.size())

torch.Size([5, 3])


"torch size" is in fact a tuple, so it supports all tuple operations.
Operations There are multiple syntaxes for operations. In the following example, we will take a look at the addition operations

In [31]:
y = torch.rand(2,2)
print(o,"\n",y)
print(o+y)

tensor([[1., 1.],
        [1., 1.]]) 
 tensor([[0.7950, 0.8437],
        [0.1418, 0.9808]])
tensor([[1.7950, 1.8437],
        [1.1418, 1.9808]])


In [32]:
torch.add(o,y)

tensor([[1.7950, 1.8437],
        [1.1418, 1.9808]])

using out option to get output as arguement

In [33]:
result = torch.empty(2,2)
torch.add(o,y,out = result)
result

tensor([[1.7950, 1.8437],
        [1.1418, 1.9808]])

Adding in place.

In [34]:
o.add_(y)

tensor([[1.7950, 1.8437],
        [1.1418, 1.9808]])

Note:
Any operation that mutates a tensor in-place is post-fixed with an "_". for example: "x.copy_(y)" 

In [35]:
index = torch.rand(5,5)
index

tensor([[0.5211, 0.7685, 0.2972, 0.2351, 0.4892],
        [0.2465, 0.2667, 0.8101, 0.1036, 0.0760],
        [0.6213, 0.1038, 0.9424, 0.2015, 0.1459],
        [0.0174, 0.3780, 0.2274, 0.6305, 0.2709],
        [0.1099, 0.1711, 0.5240, 0.0470, 0.8420]])

In [36]:
index[:,0]

tensor([0.5211, 0.2465, 0.6213, 0.0174, 0.1099])

Resizing: If you want to resize/reshape tensor, you can use torch.view:

In [37]:
x2 = torch.randn(4,4)
y = x2.view(16)

z = x2.view(-1,4)# -1 helps tensor to reshape it in required manner according to
# second arguement (4) .
print(x2,y,z,sep = "\n")
print(x2.size(),y.size(),z.size())

tensor([[-0.3063,  0.4532, -0.6943,  0.6614],
        [ 0.1181, -0.4568, -1.0777,  0.0298],
        [ 0.2421, -0.9680,  0.2643, -2.0346],
        [ 0.5116, -0.1503, -0.6523,  0.3132]])
tensor([-0.3063,  0.4532, -0.6943,  0.6614,  0.1181, -0.4568, -1.0777,  0.0298,
         0.2421, -0.9680,  0.2643, -2.0346,  0.5116, -0.1503, -0.6523,  0.3132])
tensor([[-0.3063,  0.4532, -0.6943,  0.6614],
        [ 0.1181, -0.4568, -1.0777,  0.0298],
        [ 0.2421, -0.9680,  0.2643, -2.0346],
        [ 0.5116, -0.1503, -0.6523,  0.3132]])
torch.Size([4, 4]) torch.Size([16]) torch.Size([4, 4])


NumPy.random.randn generates samples from the normal distribution (mean 0 and variance 1), while numpy.rand from a uniform distribution (in the range [0,1)).

if you have a one element tensor, use .item() to get the value as a pythong number

In [38]:
x = torch.randn(1)
x
print(x.item())

0.3138141930103302


Read later:
There are more than 100 operations including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc., are described
https://pytorch.org/docs/stable/index.html

NumPy Bridge
Converting a torch tensor to a numpy array and vice versa its a breeze.


The torch tensor and Numpy array will share their underlying memory locations.(if the torch tensor is on CPU), and changing one will change the other.

In [39]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [40]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

See how the numpy array changed in value.

In [41]:
a.add_(1)
print(a,b)

tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]


In [42]:
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1.4,out = a)

array([2.4, 2.4, 2.4, 2.4, 2.4])

## CUDA Tensors

In [43]:
#let us run this cell only if cuda is available
# we will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
  device = torch.device("cuda")
  y = torch.ones_like(x,device = device)
  x = x.to(device)
  print(z)
  print(z.to("cpu", torch.double))

Forward Propogation

In [44]:
a = torch.Tensor([2])
b = torch.Tensor([-4])
c = torch.Tensor([-2])
d = torch.Tensor([2])

e = a+b
f = c*d

g = e*f
print(e,f,g)

tensor([-2.]) tensor([-4.]) tensor([8.])


In [45]:
x = torch.tensor(-3., requires_grad=True)
y = torch.tensor(5., requires_grad=True)
z = torch.tensor(-1., requires_grad=True)

q = x + y
f = q * z
f.backward()
print("Gradient of z,y,x are:"+str(z.grad)+str(y.grad)+str(x.grad))

Gradient of z,y,x are:tensor(2.)tensor(-1.)tensor(-1.)


Fully Connected neural networks.

In [46]:
import torch
input_layer = torch.rand(10)# declaration of inputs
w1 = torch.rand(10,20)
w2 = torch.rand(20,20)
w3 = torch.rand(20,4)

h1 = torch.matmul(input_layer,w1)# first hidden layer.
h2 = torch.matmul(h1,w2)# subsequent hidden layer.
output_layer = torch.matmul(h2,w3)

print(h1,h2,output_layer,sep = "\n")

tensor([2.5902, 3.0183, 2.3186, 3.6760, 1.8882, 2.8214, 2.0038, 2.2991, 2.9564,
        2.9741, 2.9577, 2.8181, 1.9456, 3.3594, 3.1224, 3.4665, 2.3557, 2.6885,
        2.9748, 3.1396])
tensor([29.0561, 31.7675, 25.4499, 23.4698, 27.9361, 23.1501, 23.4729, 30.1408,
        21.9294, 27.8077, 20.6162, 27.0431, 31.1167, 30.8306, 25.6574, 22.3077,
        23.1437, 24.2214, 27.3733, 24.6787])
tensor([216.6026, 268.8469, 234.9943, 318.9852])


Building a neural network - Pytorch style

In [47]:
import torch.nn as nn
class Net(nn.Module):
  def __init__(self):
    super(Net, self).__init__()
    self.fc1 = nn.Linear(10,20)
    self.fc2 = nn.Linear(20,20)
    self.output = nn.Linear(20,4)


  def forward(self,x):
    x = self.fc1(x)
    x = self.fc2(x)
    x = self.output(x)
    return x


input_layer = torch.rand(10)
net = Net()
result = net(input_layer)

In [48]:
result

tensor([ 0.1937, -0.2156, -0.0699, -0.0441], grad_fn=<AddBackward0>)