<a href="https://colab.research.google.com/github/Harish-aditya/DeepLearning_using-_Pytorch./blob/main/Deep_learning_using_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import Functions.

In [37]:
from __future__ import print_function
import torch

Pytorch compared to NumPy
Matrix formation using Pytorch

In [38]:
torch.tensor([[2,3,5],[1,2,9]])

tensor([[2, 3, 5],
        [1, 2, 9]])

In [39]:
torch.rand(2,2)

tensor([[0.3859, 0.8708],
        [0.2143, 0.1002]])

In [40]:
a = torch.rand((3,5))
a

tensor([[0.9355, 0.8558, 0.5006, 0.6860, 0.0374],
        [0.9026, 0.7091, 0.1104, 0.6571, 0.0066],
        [0.7332, 0.2494, 0.7024, 0.1393, 0.9579]])

In [41]:
a.shape

torch.Size([3, 5])

Matrix formation using numpy

In [42]:
import numpy as np
np.array([[2,3,4],[1,2,3]])

array([[2, 3, 4],
       [1, 2, 3]])

In [43]:
np.random.rand(2,2)

array([[0.73588927, 0.5468706 ],
       [0.10001735, 0.34471219]])

# Construct a randomly initialized matrix and operation using Pytorch

In [44]:
a = torch.rand((2,2))
b = torch.rand((2,2))

In [45]:
torch.matmul(a,b)

tensor([[0.3186, 0.4151],
        [0.6087, 0.8439]])

In [46]:
a*b

tensor([[0.1377, 0.1941],
        [0.0424, 0.7984]])

In [47]:
a

tensor([[0.2142, 0.2571],
        [0.0602, 0.8103]])

In [48]:
a

tensor([[0.2142, 0.2571],
        [0.0602, 0.8103]])

Construct a randomly initialized matrix and operation using NumPy

In [49]:
a = np.random.rand(2,2)
b = np.random.rand(2,2)

In [50]:
np.dot(a,b)
# normal matrix multiplication
# Where the condition of number of columns of first array should be equal to number of rows of second array is checked.
# then only numpy.dot() function take place else it throws an error.

array([[0.29840869, 0.28745561],
       [0.29288571, 0.38794701]])

In [51]:
np.multiply(a,b)
# '*' 
# element wise multiplication

array([[0.28035362, 0.02249965],
       [0.12635658, 0.23048546]])

### Construct a 5x3 matrix uninitialized:

In [52]:
x = torch.empty(5,3)

In [53]:
x

tensor([[3.6240e-35, 0.0000e+00, 6.0213e-02],
        [8.1032e-01, 2.6625e-44, 0.0000e+00],
        [       nan,        nan, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

### Construct a matrix filled zeros and of dtypes long:

In [54]:
y = torch.zeros((2,2))
y

tensor([[0., 0.],
        [0., 0.]])

In [55]:
y_num = np.zeros((2,2))
y_num

array([[0., 0.],
       [0., 0.]])

In [56]:
x = torch.zeros(5,3,dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


### Construct a matrix of ones

In [57]:
o = torch.ones(2,2)

In [58]:
o

tensor([[1., 1.],
        [1., 1.]])

In [59]:
o_num = np.ones((2,2))
o_num

array([[1., 1.],
       [1., 1.]])

### Construst identity matrix

In [60]:
c_num = np.identity(5)
c_num

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [61]:
c = torch.eye(2)
c

tensor([[1., 0.],
        [0., 1.]])

## Converting NumPy array to torch tensor see how changing the np array changed the Torch Tensor automatically

In [62]:
d = torch.from_numpy(c_num)

In [63]:
d

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]], dtype=torch.float64)

In [64]:
d_num = c.numpy()
d_num

array([[1., 0.],
       [0., 1.]], dtype=float32)

## create a tensor based on an existing tensor.

In [65]:
x1 = x.new_ones(5,3, dtype=torch.double)
print(x1)

x2 = x.new_ones(5,3, dtype=torch.float)
print(x2)

x3 = torch.randn_like(x, dtype = float)
print(x3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[ 0.8252,  0.9380,  2.3256],
        [ 0.9779, -1.1492, -0.6504],
        [ 0.9263,  0.7974, -0.7171],
        [ 0.4547,  1.9776, -0.1276],
        [ 0.0383,  1.1650,  0.2044]], dtype=torch.float64)


Size of the array of tensors.

In [66]:
print(x.size())

torch.Size([5, 3])


"torch size" is in fact a tuple, so it supports all tuple operations.
Operations There are multiple syntaxes for operations. In the following example, we will take a look at the addition operations

In [70]:
y = torch.rand(2,2)
print(o,"\n",y)
print(o+y)

tensor([[1., 1.],
        [1., 1.]]) 
 tensor([[0.4086, 0.1788],
        [0.3081, 0.3803]])
tensor([[1.4086, 1.1788],
        [1.3081, 1.3803]])


In [72]:
torch.add(o,y)

tensor([[1.4086, 1.1788],
        [1.3081, 1.3803]])

using out option to get output as arguement

In [73]:
result = torch.empty(2,2)
torch.add(o,y,out = result)
result

tensor([[1.4086, 1.1788],
        [1.3081, 1.3803]])

Adding in place.

In [75]:
o.add_(y)

tensor([[1.4086, 1.1788],
        [1.3081, 1.3803]])

Note:
Any operation that mutates a tensor in-place is post-fixed with an "_". for example: "x.copy_(y)" 

In [76]:
index = torch.rand(5,5)
index

tensor([[0.0656, 0.6601, 0.8196, 0.7141, 0.8348],
        [0.4806, 0.9646, 0.4859, 0.8044, 0.4466],
        [0.0786, 0.8191, 0.0720, 0.0494, 0.4057],
        [0.2796, 0.0910, 0.1765, 0.0071, 0.5349],
        [0.1944, 0.7046, 0.5868, 0.6347, 0.4808]])

In [83]:
index[:,0]

tensor([0.0786, 0.2796, 0.1944])

Resizing: If you want to resize/reshape tensor, you can use torch.view:

In [85]:
x2 = torch.randn(4,4)
y = x2.view(16)
y 

tensor([-0.2731,  1.4469, -1.6586,  0.8395, -0.0814,  0.2282,  0.2367, -0.0460,
         0.9230, -0.2201,  0.7442, -0.2814,  0.1868,  0.0904,  0.2908,  0.9718])

NumPy 