<a href="https://colab.research.google.com/github/Harish-aditya/DeepLearning_using-_Pytorch./blob/main/Deep_learning_using_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import Functions.

In [1]:
from __future__ import print_function
import torch

Pytorch compared to NumPy
Matrix formation using Pytorch

In [2]:
torch.tensor([[2,3,5],[1,2,9]])

tensor([[2, 3, 5],
        [1, 2, 9]])

In [3]:
torch.rand(2,2)

tensor([[0.6953, 0.0759],
        [0.5712, 0.7705]])

In [4]:
a = torch.rand((3,5))
a

tensor([[0.8481, 0.1105, 0.1455, 0.7326, 0.2395],
        [0.7929, 0.1775, 0.5729, 0.4199, 0.2695],
        [0.9742, 0.4484, 0.4860, 0.7168, 0.4628]])

In [5]:
a.shape

torch.Size([3, 5])

Matrix formation using numpy

In [6]:
import numpy as np
np.array([[2,3,4],[1,2,3]])

array([[2, 3, 4],
       [1, 2, 3]])

In [7]:
np.random.rand(2,2)

array([[0.80177449, 0.90648848],
       [0.13811981, 0.83076884]])

# Construct a randomly initialized matrix and operation using Pytorch

In [8]:
a = torch.rand((2,2))
b = torch.rand((2,2))

In [9]:
torch.matmul(a,b)

tensor([[0.1093, 0.1742],
        [0.1579, 0.2741]])

In [10]:
a*b

tensor([[0.0980, 0.0131],
        [0.0181, 0.2533]])

In [11]:
a

tensor([[0.2615, 0.0222],
        [0.0354, 0.2825]])

In [12]:
a

tensor([[0.2615, 0.0222],
        [0.0354, 0.2825]])

Construct a randomly initialized matrix and operation using NumPy

In [13]:
a = np.random.rand(2,2)
b = np.random.rand(2,2)

In [14]:
np.dot(a,b)
# normal matrix multiplication
# Where the condition of number of columns of first array should be equal to number of rows of second array is checked.
# then only numpy.dot() function take place else it throws an error.

array([[0.49057865, 0.15938908],
       [0.66578296, 0.20393805]])

In [15]:
np.multiply(a,b)
# '*' 
# element wise multiplication

array([[0.21134266, 0.07021025],
       [0.07843906, 0.18421557]])

### Construct a 5x3 matrix uninitialized:

In [16]:
x = torch.empty(5,3)

In [17]:
x

tensor([[1.7250e-35, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 7.9286e-01],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 4.6281e-01]])

### Construct a matrix filled zeros and of dtypes long:

In [18]:
y = torch.zeros((2,2))
y

tensor([[0., 0.],
        [0., 0.]])

In [19]:
y_num = np.zeros((2,2))
y_num

array([[0., 0.],
       [0., 0.]])

In [20]:
x = torch.zeros(5,3,dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


### Construct a matrix of ones

In [21]:
o = torch.ones(2,2)

In [22]:
o

tensor([[1., 1.],
        [1., 1.]])

In [23]:
o_num = np.ones((2,2))
o_num

array([[1., 1.],
       [1., 1.]])

### Construst identity matrix

In [24]:
c_num = np.identity(5)
c_num

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
c = torch.eye(2)
c

tensor([[1., 0.],
        [0., 1.]])

## Converting NumPy array to torch tensor see how changing the np array changed the Torch Tensor automatically

In [26]:
d = torch.from_numpy(c_num)

In [27]:
d

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]], dtype=torch.float64)

In [28]:
d_num = c.numpy()
d_num

array([[1., 0.],
       [0., 1.]], dtype=float32)

## create a tensor based on an existing tensor.

In [29]:
x1 = x.new_ones(5,3, dtype=torch.double)
print(x1)

x2 = x.new_ones(5,3, dtype=torch.float)
print(x2)

x3 = torch.randn_like(x, dtype = float)
print(x3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[ 2.5628,  1.4494,  1.0240],
        [ 1.3613, -0.4953,  0.0694],
        [-1.0982, -1.3893,  2.0967],
        [ 1.1342, -0.4159,  0.9585],
        [ 1.2520,  0.7083,  0.3608]], dtype=torch.float64)


Size of the array of tensors.

In [30]:
print(x.size())

torch.Size([5, 3])


"torch size" is in fact a tuple, so it supports all tuple operations.
Operations There are multiple syntaxes for operations. In the following example, we will take a look at the addition operations

In [31]:
y = torch.rand(2,2)
print(o,"\n",y)
print(o+y)

tensor([[1., 1.],
        [1., 1.]]) 
 tensor([[0.5381, 0.5996],
        [0.2343, 0.1869]])
tensor([[1.5381, 1.5996],
        [1.2343, 1.1869]])


In [32]:
torch.add(o,y)

tensor([[1.5381, 1.5996],
        [1.2343, 1.1869]])

using out option to get output as arguement

In [33]:
result = torch.empty(2,2)
torch.add(o,y,out = result)
result

tensor([[1.5381, 1.5996],
        [1.2343, 1.1869]])

Adding in place.

In [34]:
o.add_(y)

tensor([[1.5381, 1.5996],
        [1.2343, 1.1869]])

Note:
Any operation that mutates a tensor in-place is post-fixed with an "_". for example: "x.copy_(y)" 

In [35]:
index = torch.rand(5,5)
index

tensor([[0.1809, 0.7233, 0.4746, 0.5235, 0.7496],
        [0.5179, 0.1635, 0.1277, 0.5112, 0.8371],
        [0.3136, 0.6976, 0.7300, 0.6498, 0.7469],
        [0.7414, 0.2502, 0.8491, 0.5988, 0.9989],
        [0.9256, 0.1850, 0.3398, 0.2448, 0.6387]])

In [36]:
index[:,0]

tensor([0.1809, 0.5179, 0.3136, 0.7414, 0.9256])

Resizing: If you want to resize/reshape tensor, you can use torch.view:

In [37]:
x2 = torch.randn(4,4)
y = x2.view(16)

z = x2.view(-1,4)# -1 helps tensor to reshape it in required manner according to
# second arguement (4) .
print(x2,y,z,sep = "\n")
print(x2.size(),y.size(),z.size())

tensor([[-0.1017, -0.4728,  0.2401, -0.8237],
        [ 1.2091,  2.2582,  0.0646,  1.3728],
        [ 0.1244,  0.2047, -0.4426,  1.4835],
        [ 1.0536, -0.5399,  1.4713, -0.7068]])
tensor([-0.1017, -0.4728,  0.2401, -0.8237,  1.2091,  2.2582,  0.0646,  1.3728,
         0.1244,  0.2047, -0.4426,  1.4835,  1.0536, -0.5399,  1.4713, -0.7068])
tensor([[-0.1017, -0.4728,  0.2401, -0.8237],
        [ 1.2091,  2.2582,  0.0646,  1.3728],
        [ 0.1244,  0.2047, -0.4426,  1.4835],
        [ 1.0536, -0.5399,  1.4713, -0.7068]])
torch.Size([4, 4]) torch.Size([16]) torch.Size([4, 4])


NumPy.random.randn generates samples from the normal distribution (mean 0 and variance 1), while numpy.rand from a uniform distribution (in the range [0,1)).

if you have a one element tensor, use .item() to get the value as a pythong number

In [38]:
x = torch.randn(1)
x
print(x.item())

-2.003523588180542


Read later:
There are more than 100 operations including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc., are described
https://pytorch.org/docs/stable/index.html

NumPy Bridge
Converting a torch tensor to a numpy array and vice versa its a breeze.


The torch tensor and Numpy array will share their underlying memory locations.(if the torch tensor is on CPU), and changing one will change the other.

In [39]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [40]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

See how the numpy array changed in value.

In [41]:
a.add_(1)
print(a,b)

tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]


In [42]:
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1.4,out = a)

array([2.4, 2.4, 2.4, 2.4, 2.4])

## CUDA Tensors

In [43]:
#let us run this cell only if cuda is available
# we will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
  device = torch.device("cuda")
  y = torch.ones_like(x,device = device)
  x = x.to(device)
  print(z)
  print(z.to("cpu", torch.double))

Forward Propogation

In [44]:
a = torch.Tensor([2])
b = torch.Tensor([-4])
c = torch.Tensor([-2])
d = torch.Tensor([2])

e = a+b
f = c*d

g = e*f
print(e,f,g)

tensor([-2.]) tensor([-4.]) tensor([8.])


In [45]:
x = torch.tensor(-3., requires_grad=True)
y = torch.tensor(5., requires_grad=True)
z = torch.tensor(-1., requires_grad=True)

q = x + y
f = q * z
f.backward()
print("Gradient of z,y,x are:"+str(z.grad)+str(y.grad)+str(x.grad))

Gradient of z,y,x are:tensor(2.)tensor(-1.)tensor(-1.)


Fully Connected neural networks.

In [46]:
import torch
input_layer = torch.rand(10)# declaration of inputs
w1 = torch.rand(10,20)
w2 = torch.rand(20,20)
w3 = torch.rand(20,4)

h1 = torch.matmul(input_layer,w1)# first hidden layer.
h2 = torch.matmul(h1,w2)# subsequent hidden layer.
output_layer = torch.matmul(h2,w3)

print(h1,h2,output_layer,sep = "\n")

tensor([2.6187, 3.4613, 3.8800, 2.9597, 2.3460, 2.6737, 3.2654, 3.0053, 2.5287,
        2.0482, 3.2351, 2.8313, 2.8099, 2.3694, 2.1905, 3.4951, 2.7852, 2.8221,
        2.9005, 3.2813])
tensor([33.1590, 23.8894, 33.0219, 24.6570, 25.3319, 34.3669, 30.7313, 35.2582,
        30.8955, 23.8908, 26.0742, 34.8628, 30.6363, 36.8704, 24.0531, 28.0790,
        26.4971, 29.7101, 28.5470, 30.8682])
tensor([298.2157, 345.4110, 250.3767, 336.3159])


Building a neural network - Pytorch style

In [47]:
import torch.nn as nn
class Net(nn.Module):
  def __init__(self):
    super(Net, self).__init__()
    self.fc1 = nn.Linear(10,20)
    self.fc2 = nn.Linear(20,20)
    self.output = nn.Linear(20,4)


  def forward(self,x):
    x = self.fc1(x)
    x = self.fc2(x)
    x = self.output(x)
    return x


input_layer = torch.rand(10)
net = Net()
result = net(input_layer)

In [48]:
result

tensor([-0.1414,  0.1457, -0.0846, -0.2057], grad_fn=<AddBackward0>)

## Backward propagation

In [55]:
x = torch.tensor(4.,requires_grad=True)
y = torch.tensor(-3.,requires_grad=True)
z = torch.tensor(5.,requires_grad=True)

q = x+y
f = q*z

f.backward()
print(str(x.grad))
print(str(y.grad))
print(str(z.grad)) 

tensor(5.)
tensor(5.)
tensor(1.)


Example:
Initialize random tensors x,y and z each having shape (1000,1000).
Multiply x with y, putting the result in tensor q.
Do an elementwise multiplication of tensor z with tensor q. putting the results in f.


In [56]:
x = torch.rand(1000,1000, requires_grad = True)
y = torch.rand(1000,1000, requires_grad = True)
z = torch.rand(1000,1000, requires_grad = True)

q = torch.matmul(x,y)
f = z*q
mean_f = torch.mean(f)
print(mean_f)

mean_f.backward()

print(str(x.grad))
print(str(y.grad))
print(str(z.grad))

tensor(125.1320, grad_fn=<MeanBackward0>)
tensor([[0.0002, 0.0002, 0.0002,  ..., 0.0002, 0.0002, 0.0002],
        [0.0002, 0.0002, 0.0002,  ..., 0.0002, 0.0002, 0.0002],
        [0.0002, 0.0002, 0.0002,  ..., 0.0002, 0.0002, 0.0002],
        ...,
        [0.0002, 0.0002, 0.0002,  ..., 0.0003, 0.0002, 0.0002],
        [0.0003, 0.0003, 0.0002,  ..., 0.0003, 0.0003, 0.0003],
        [0.0002, 0.0002, 0.0002,  ..., 0.0003, 0.0002, 0.0003]])
tensor([[0.0003, 0.0002, 0.0003,  ..., 0.0002, 0.0003, 0.0003],
        [0.0003, 0.0002, 0.0003,  ..., 0.0002, 0.0003, 0.0003],
        [0.0003, 0.0002, 0.0003,  ..., 0.0002, 0.0003, 0.0003],
        ...,
        [0.0003, 0.0002, 0.0003,  ..., 0.0002, 0.0002, 0.0002],
        [0.0003, 0.0003, 0.0003,  ..., 0.0002, 0.0003, 0.0003],
        [0.0003, 0.0002, 0.0003,  ..., 0.0002, 0.0003, 0.0002]])
tensor([[0.0003, 0.0002, 0.0003,  ..., 0.0003, 0.0002, 0.0002],
        [0.0002, 0.0002, 0.0002,  ..., 0.0003, 0.0002, 0.0003],
        [0.0003, 0.0003, 0.0003,  